version: '3'
services:
  springboot-docker-compose-app-container:
    image: siddhartha23/milestone-3
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/siddhartha23/milestone-3
    ports:
      - "8080:8080"